# name: my-friday-app

services:
  development-server:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: my-friday-app-development
    ports:
      - "3001:3000"
    develop:
      watch:
        - action: sync
          path: ../../
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ../../